# Generated by Django 6.0.2 on 2026-02-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ім'я'")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Прізвище"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=100, verbose_name="Тел.номер"),
                ),
                ("email", models.CharField(max_length=100, verbose_name="Е-мейл")),
                (
                    "address",
                    models.CharField(max_length=250, verbose_name="Поточна адреса"),
                ),
                (
                    "registration_date",
                    models.DateTimeField(verbose_name="Дата реєстрації"),
                ),
            ],
        ),
    ]
