# Generated by Django 6.0.2 on 2026-02-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Персона", "verbose_name_plural": "Персони"},
        ),
        migrations.AddField(
            model_name="person",
            name="login",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="parol",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
