# Generated by Django 6.0.2 on 2026-02-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_alter_person_options_person_login_person_parol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="registration_date",
            field=models.DateField(verbose_name="Дата реєстрації"),
        ),
    ]
